[package]
name = "aws-ecs-1-nvidia"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[package.metadata.build-variant.image-layout]
os-image-size-gib = 4

[package.metadata.build-variant]
kernel-parameters = [
    "console=tty0",
    "console=ttyS0,115200n8",
    "net.ifnames=0",
    "netdog.default-interface=eth0:dhcp4,dhcp6?",
    "quiet",
]
included-packages = [
# core
    "early-boot-config",
    "release",
    "kernel-5.10",
    "aws-data-providers",
# docker
    "docker-cli",
    "docker-engine",
    "docker-init",
    "docker-proxy",
# ecs
    "ecs-agent",
# NVIDIA support
    "ecs-gpu-init",
    "nvidia-container-toolkit",
    "kmod-5.10-nvidia-tesla-470",
]

[lib]
path = "../variants.rs"

[build-dependencies]
# core
early-boot-config = { path = "../../packages/early-boot-config" }
early-boot-config-ec2-identity-doc = { path = "../../packages/early-boot-config-ec2-identity-doc" }
early-boot-config-ec2-imds = { path = "../../packages/early-boot-config-ec2-imds" }
early-boot-config-local-defaults = { path = "../../packages/early-boot-config-local-defaults" }
early-boot-config-local-overrides = { path = "../../packages/early-boot-config-local-overrides" }
early-boot-config-local = { path = "../../packages/early-boot-config-local" }
early-boot-config-providers = { path = "../../packages/early-boot-config-providers" }
release = { path = "../../packages/release" }
kernel-5_10 = { path = "../../packages/kernel-5.10" }
# docker
docker-cli = { path = "../../packages/docker-cli" }
docker-engine = { path = "../../packages/docker-engine" }
docker-init = { path = "../../packages/docker-init" }
docker-proxy = { path = "../../packages/docker-proxy" }
# ecs
ecs-agent = { path = "../../packages/ecs-agent" }
# NVIDIA
ecs-gpu-init = { path = "../../packages/ecs-gpu-init" }
nvidia-container-toolkit = { path = "../../packages/nvidia-container-toolkit" }
kmod-5_10-nvidia = { path = "../../packages/kmod-5.10-nvidia" }
