[package]
# This is the vmware-k8s-1.25 variant. "." is not allowed in crate names, but
# we don't use this crate name anywhere.
name = "vmware-k8s-1_25"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[package.metadata.build-variant.image-layout]
partition-plan = "unified"

[package.metadata.build-variant.image-features]
grub-set-private-var = true

[package.metadata.build-variant]
image-format = "vmdk"
supported-arches = ["x86_64"]
kernel-parameters = [
    "console=tty1",
    # Only reserve if there are at least 2GB
    "crashkernel=2G-:256M",
    "net.ifnames=0",
    "netdog.default-interface=eth0:dhcp4,dhcp6?",
    "quiet",
]
included-packages = [
    "cni",
    "cni-plugins",
    "early-boot-config",
    "kernel-5.15",
    "kubelet-1.25",
    "open-vm-tools",
    "release",
    "vmware-data-providers",
]

[lib]
path = "../variants.rs"

[build-dependencies]
cni = { path = "../../packages/cni" }
cni-plugins = { path = "../../packages/cni-plugins" }
early-boot-config = { path = "../../packages/early-boot-config" }
early-boot-config-local-defaults = { path = "../../packages/early-boot-config-local-defaults" }
early-boot-config-local-overrides = { path = "../../packages/early-boot-config-local-overrides" }
early-boot-config-local = { path = "../../packages/early-boot-config-local" }
early-boot-config-vmware-cd-rom = { path = "../../packages/early-boot-config-vmware-cd-rom" }
early-boot-config-vmware-guestinfo = { path = "../../packages/early-boot-config-vmware-guestinfo" }
early-boot-config-providers = { path = "../../packages/early-boot-config-providers" }
kernel-5_15 = { path = "../../packages/kernel-5.15" }
kubernetes-1_25 = { path = "../../packages/kubernetes-1.25" }
open-vm-tools = { path = "../../packages/open-vm-tools" }
release = { path = "../../packages/release" }
